UNREACHABLE_MINER_SCORE = -10
NO_STATEMENTS_PROVIDED_SCORE = -5
INVALID_RESPONSE_MINER_SCORE = -10
SSL_DOMAIN_REQUIRED = -2
APPROVED_URL_MULTIPLIER = 3 #

EXCERPT_TOO_SIMILAR = -5
BLACKLISTED_URL_SCORE =-5
SNIPPET_NOT_VERIFIED_IN_URL = -1
SNIPPET_NOT_CONTEXT_SIMILAR = 0 # NOT PENALIZING
NO_SNIPPET_PROVIDED = -5
USING_SEARCH_AS_EVIDENCE = -5
UNRELATED_SNIPPET_PROVIDED = -5
FAKE_MINER_URL = -5
UNRELATED_PAGE_SNIPPET = -5
INVALID_SNIPPET_EXCERPT = -5
IS_SEARCH_WEB_PAGE = -5

COULD_NOT_GET_PAGE_TEXT_FROM_URL=-1
DOMAIN_REGISTERED_RECENTLY = -1

# Gaming responses
SNIPPET_SAME_AS_STATEMENT = -10
