UNREACHABLE_MINER_SCORE = -10
NO_STATEMENTS_PROVIDED_SCORE = -5
INVALID_RESPONSE_MINER_SCORE = -10
SSL_DOMAIN_REQUIRED = -2
APPROVED_URL_MULTIPLIER = 3 #

SNIPPET_NOT_VERIFIED_IN_URL = -1
NO_SNIPPET_PROVIDED = -5
COULD_NOT_GET_PAGE_TEXT_FROM_URL=-1
DOMAIN_REGISTERED_RECENTLY = -1

# Gaming responses
SNIPPET_SAME_AS_STATEMENT = -10
